### ISSUE TITLE
コンボ(中)

### ISSUE THREAD

**Issue by KudoRiku0** [KudoRiku0/tumu#11]
コンボ（優先度：中）
一定時間内に連続でツムを消していくと、どんどんコンボがつながる
・一定時間以内に連続して消すとコンボと判定 → 「コンボ判定処理実装」
・コンボと判定したらコンボ数を表示（View）→「コンボ数表示実装」
・コンボ時にはスコアにコンボボーナスを加算 → 「スコアにコンボボーナスを加算」 #

* deltimeを使って時間を測って時間内に消せればtime+してupdate内にif文で都度判定をかけていく感じ？

**Comment by choushi** [comment]
#27 #28 #29 に分割したので、こちらはcloseします
