### ISSUE TITLE
デバッグ用の collider 表示の実装

### ISSUE THREAD

**Issue by jtakakura** [KudoRiku0/tumu#14]
デバッグ可能なようにスプライトの描画とは別に、 collider の形状も線で描画するようにしてください。
最終的には画面に隠しメニューを作って、そこから On / Off できるようになったらいいですが、当面はスクリプトにベタに boolean 型のフラグ変数を持てばいいかと思います。

**Comment by choushi** [comment]
高倉さん案
<pre>
1. Collider とその形状( Circle か Box かなど)の取得
2. CreatePrimitive でその形状を作る
3. Collider の種別ごとに設定値(円なら radius とか)を元に transform したり、色塗ったりする
</pre>
まずは、これで行けそうか調査から

**Comment by KudoRiku0** [comment]
ちょうさん高倉さんレビューお願いします
