### ISSUE TITLE
【コンボ】コンボ判定処理実装

### ISSUE THREAD

**Issue by KudoRiku0** [KudoRiku0/tumu#27]

**Comment by choushi** [comment]
一定時間以内に連続して消すとコンボと判定する

**Comment by KudoRiku0** [comment]
ツムを消す→4秒のコンボ継続するための時間を＋→deltatimeでマイナスしていく→0になった瞬間コンボ数リセット判定→0にならない場合コンボ数＋1とタイムを4秒にリセット
