### ISSUE TITLE
時間切れ後、再スタートさせる

### ISSUE THREAD

**Issue by choushi** [KudoRiku0/tumu#40]
タイムアウト後にまた最初からツムを落とすところから始める

**Comment by KudoRiku0** [comment]
つまりリセットボタンですよね？

**Comment by choushi** [comment]
そうだね
ボタンがあった方が良いか

では、リスタートボタンでお願いします

**Comment by KudoRiku0** [comment]
ゲームオーバー後にリスタートボタンを真ん中に表示してゲームシーンをロードし直す感じでいいですか

**Comment by choushi** [comment]
デザイン的なことはこだわってないから
それでいいんじゃないかな

**Comment by KudoRiku0** [comment]
わかりました

**Comment by jtakakura** [comment]
これ、不要だったら、この Issue 対応する際に削除してください

https://github.com/KudoRiku0/tumu/blob/master/%5D
