### ISSUE TITLE
マジカルボム(中)

### ISSUE THREAD

**Issue by KudoRiku0** [KudoRiku0/tumu#6]
７つ以上つなげるとマジカルボム発生（優先度：中）
マジカルボムをタップするとまわりのツムを纏めて消す

マジカルボム種類
ノーマル・・・まわりのツムを纏めてけすだけ
コインボム・・・ノーマル効果＋コイン＋１０枚
スターボム・・・ノーマル効果＋経験値＋１０
タイムボム・・・ノーマル効果＋タイム２秒追加

・７つ連鎖でボム発生させるという判定処理実装
・ボムを画面に発生させる処理実装
・ボムタップで周りのツムを消す処理実装
・ボムタップ時に同時に発生する効果（コイン加算、タイム加算等）実装

**Comment by choushi** [comment]
#15 #16 #17 #18に別issueとして登録しなおしたので、こちらはcloseします
